# Generated by Django 4.2.7 on 2024-01-17 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_expense_income"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Signdata",
        ),
    ]
