# Generated by Django 4.2.7 on 2024-01-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_delete_signdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="spent",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="income",
            name="amount",
            field=models.IntegerField(null=True),
        ),
    ]
